# Ejercicio Vinos
## Emilio León y Sofía Blancas
### 09/03/2026

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression

In [2]:
df_vinos = pd.read_csv("wines-1-1.csv")
df_vinos.head()

   Year   Price  WinterRain     AGST  HarvestRain  Age  FrancePop
0  1952  7.4950         600  17.1167          160   31  43183.569
1  1953  8.0393         690  16.7333           80   30  43495.030
2  1955  7.6858         502  17.1500          130   28  44217.857
3  1957  6.9845         420  16.1333          110   26  45152.252
4  1958  6.7772         582  16.4167          187   25  45653.805

In [3]:
df_vinos["Price"].max()

8.4937

In [4]:
df_vinos["Price"].min()

6.2049

#### El precio esta entre 8.5 y 6.2 redondeando, tal vez normalizando podríamos ver la predicción de la calidad

In [5]:
df_vinos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Year         27 non-null     int64
 1   Price        27 non-null     float64
 2   WinterRain   27 non-null     int64
 3   AGST         27 non-null     float64
 4   HarvestRain  27 non-null     int64
 5   Age          27 non-null     int64
 6   FrancePop    27 non-null     float64
dtypes: float64(3), int64(4)
memory usage: 1.6 KB

#### Podemos predecir la calidad del vino? según su precio?
#### Nuestra y será el precio.
#### Nuestras x serán WinterRain, AGST, HarvestRain, y Age
#### Son las más determinantes debido a que son las que más información nos dan sobre la calidad del vino.

In [6]:
df_vinos[["Price", "Year", "WinterRain", "AGST", "HarvestRain", "Age"]].corr()

                Price      Year  WinterRain      AGST  HarvestRain       Age
Price        1.000000 -0.460409    0.134880  0.667525    -0.507185  0.460409
Year        -0.460409  1.000000    0.051184 -0.294883    -0.058850 -1.000000
WinterRain   0.134880  0.051184    1.000000 -0.321132    -0.267989 -0.051184
AGST         0.667525 -0.294883   -0.321132  1.000000    -0.027084  0.294883
HarvestRain -0.507185 -0.058850   -0.267989 -0.027084     1.000000  0.058850
Age          0.460409 -1.000000   -0.051184  0.294883     0.058850  1.000000

In [7]:
df_vinos[["WinterRain", "AGST", "HarvestRain", "Age"]].corr()

             WinterRain      AGST  HarvestRain       Age
WinterRain     1.000000 -0.321132    -0.267989 -0.051184
AGST          -0.321132  1.000000    -0.027084  0.294883
HarvestRain   -0.267989 -0.027084     1.000000  0.058850
Age           -0.051184  0.294883     0.058850  1.000000

#### Ninguna de nuestras variables tienen una correlación alta como para excluirlas.

In [8]:
X = df_vinos[["WinterRain", "AGST", "HarvestRain", "Age"]]
y = df_vinos["Price"]

In [9]:
lr = LinearRegression()
lr.fit(X, y)

LinearRegression()

In [10]:
a0 = lr.intercept_
a1 = lr.coef_[0]
a2 = lr.coef_[1]
a3 = lr.coef_[2]
a4 = lr.coef_[3]
print("La ecuación es: y =", a0,"+ ", a1,"x1 + ", a2,"x2 + ", a3,"x3 + ", a4,"x4")

La ecuación es: y = -3.6515703302352254 +  0.001166719144632399 x1 +  0.6163915583348174 x2 +  -0.0038605996477244935 x3 +  0.02384801420540343 x4

In [11]:
R2 = lr.score(X, y)
R2

0.8275317042479997

#### La regresión es bastante buena.

In [12]:
dic = {'WinterRain': [600], 'AGST': [15], 'HarvestRain': [150], 'Age': [15]}
df_predic = pd.DataFrame(dic)
df_predic

   WinterRain  AGST  HarvestRain  Age
0         600    15          150   15

In [13]:
price_predic = lr.predict(df_predic)
price_predic

array([6.0729648])

In [14]:
df_predic['Price'] = price_predic
df_predic

   WinterRain  AGST  HarvestRain  Age     Price
0         600    15          150   15  6.072965

In [15]:
scaler = StandardScaler()

In [21]:
# Separando la normalización de X en fit y transform (de métodos en vez de 1)
X_fit = scaler.fit(X)
X_trans = pd.DataFrame(X_fit.transform(X), columns=X.columns)
X_trans

    WinterRain      AGST  HarvestRain       Age
0    -0.066397  0.987712     0.211788  1.830745
1     0.644375  0.395009    -0.903972  1.707170
2    -0.840349  1.039191    -0.206622  1.460019
3    -1.487941 -0.532538    -0.485562  1.212869
4    -0.208552 -0.094427     0.588357  1.089293
5    -0.974606  1.554444     0.588357  0.965718
6     1.220890 -0.094427     2.024898  0.842143
7     1.750020  1.322557    -1.489746  0.718567
8     0.699657 -0.274835    -1.294488  0.594992
9    -0.003217 -1.176565     0.142053  0.471417
10   -1.630096  1.219599    -0.680820  0.347842
11   -0.050602 -1.717635     1.704117  0.224266
12    1.663148  0.085827    -0.820290  0.100691
13    0.833914 -0.377947    -0.373986 -0.022884
14    0.012577 -0.429426     2.052792 -0.146460
15   -0.263834  0.111644     1.383336 -0.270035
16    0.107347  0.292052    -0.778449 -0.393610
17   -0.453373  0.446643    -0.457668 -0.517185
18   -0.571835 -2.310338     0.183894 -0.640761
19   -1.835430  0.910417    -0.304251 -0.764336
20   -0.271731 -0.274835     0.546516 -0.887911
21   -0.287526  0.730009     0.365205 -1.011487
22   -1.503736  1.812147     1.425177 -1.135062
23    1.678943 -1.382790    -0.806343 -1.258637
24    1.220890 -1.021974    -1.308435 -1.382213
25    0.857606 -0.480905    -0.318198 -1.505788
26   -0.240142 -0.738608    -0.987654 -1.629363

In [22]:
#También necesitamos normalizar el df de prueba
dic = {'WinterRain': [600], 'AGST': [15], 'HarvestRain': [150], 'Age': [15]}
df_predic1 = pd.DataFrame(dic)
df_predic1

   WinterRain  AGST  HarvestRain  Age
0         600    15          150   15

In [25]:
df_predic_norm = pd.DataFrame(X_fit.transform(df_predic1), columns=df_predic1.columns)
df_predic_norm

   WinterRain      AGST  HarvestRain      Age
0   -0.066397 -2.284521     0.072318 -0.14646

In [26]:
# Separando la normalización de y en fit y transform (2 métodos en vez de 1)
y_fit = scaler.fit(df_vinos[['Price']])
y_trans = pd.DataFrame(X_fit.transform(df_vinos[["Price"]]), columns=df_vinos[["Price"]].columns)
# Usamos en la transformación de y X_fit para que la columna price esté normalizada con x

In [27]:
# Hacemos una nueva regresión con los valores normalizados
reg = LinearRegression()
reg.fit(X_trans, y_trans)

LinearRegression()

In [28]:
# Calculamos los coeficientes, el intercepto y R2
coef_n = reg.coef_
intercept_n = reg.intercept_
r2_n = reg.score(X_trans, y_trans)
print("Coeficientes: ", coef_n, "Intercept: ", intercept_n, "R2: ", r2_n)

Coeficientes:  [[ 0.23723595  0.64028562 -0.44450433  0.30990071]] Intercept:  [2.19206992e-15] R2:  0.8275317042479993

In [29]:
#Ahora podemos hacer la predicción
res_norm = reg.predict(df_predic_norm)
res_norm

array([[-1.55603127]])

In [30]:
# El precio real deberá ser transformado usando el objeto scaler
precio = X_fit.inverse_transform(res_norm)
precio

array([[6.0729648]])