# Ejercicio Propinas
##  Emilio León
### 05/02/2026

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df_propinas = pd.read_csv("tips.csv", header=0)
df_propinas

     total_bill   tip smoker   day    time  size
0         16.99  1.01     No   Sun  Dinner     2
1         10.34  1.66     No   Sun  Dinner     3
2         21.01  3.50     No   Sun  Dinner     3
3         23.68  3.31     No   Sun  Dinner     2
4         24.59  3.61     No   Sun  Dinner     4
..          ...   ...    ...   ...     ...   ...
239       29.03  5.92     No   Sat  Dinner     3
240       27.18  2.00    Yes   Sat  Dinner     2
241       22.67  2.00    Yes   Sat  Dinner     2
242       17.82  1.75     No   Sat  Dinner     2
243       18.78  3.00     No  Thur  Dinner     2

[244 rows x 6 columns]

In [3]:
df_propinas["day"].unique()

array(['Sun', 'Sat', 'Thur', 'Fri'], dtype=object)

### El mesero trabajó Jueves, Viernes, Sábado y Domingo

In [4]:
df_propinas.groupby("day")[["tip"]].sum()

         tip
day
Fri    51.96
Sat   260.40
Sun   247.39
Thur  171.83

### Como no tenemos las fechas de los días no puedo saber exactamente cuántas propinas recaudó en una sola fecha.

### Pregunta, quién deja más propinas? Fumadores o no fumadores?

In [5]:
df_propinas.groupby("smoker")[["tip"]].sum()

           tip
smoker
No      451.77
Yes     279.81

### Los fumadores dejaron más propinas que los no fumadores.
### Pero esto puede depender de la cantidad de fumadores.

In [8]:
df_propinas["smoker"].value_counts()

smoker
No     151
Yes     93
Name: count, dtype: int64

### En proporción son casi el doble de no fumadores.
### Pregunta, en promedio cuánta propina deja cada uno?

In [9]:
df_propinas.groupby("smoker")[["tip"]].mean()

             tip
smoker
No      2.991854
Yes     3.008710

### En proporción dejan casi lo mismo, aunque los fumadores dejan poquito más

### Pregunta, Según la suam total de propinas por día
### El día donde más propinas recibe es el sábado
### Pero si sacamos cuánto recibe por promedio al día?

In [10]:
df_propinas["day"].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

### Porque en comparación el día que más recibió (sábado)
### Fue el día que más trabjó
### Y lo mismo con el menor (el día viernes)

In [11]:
df_propinas.groupby("day")[["tip"]].mean()

           tip
day
Fri   2.734737
Sat   2.993103
Sun   3.255132
Thur  2.771452

### En promedio, al día recibía al rededor de 3 dólares
### Sin embargo no cambia tanto del viernes al sábado
### Y el día donde más propinas recibia era el domingo.